# Scraping Data From a Real Website + Pandas 2

In [4]:
from bs4 import BeautifulSoup
import requests

In [5]:
url = 'https://companiesmarketcap.com/inr/'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [6]:
soup

<!DOCTYPE html>
<html lang="en-IN">
<head>
<title>Companies ranked by Market Cap - CompaniesMarketCap.com</title>
<meta charset="utf-8"/>
<link href="https://companiesmarketcap.com/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/img/icons/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/img/icons/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/img/icons/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/img/icons/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/img/icons/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/img/icons/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/img/icons/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/img/icons/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/img/icons/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/img/icons/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/img/icons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/img/icons/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/img/icons/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/img/icons/manifest.json" rel="manifest"/>
<link href="https://companiesmarketcap.com/de/" hreflang="de" rel="alternate"/>
<link href="https://companiesmarketcap.com/fr/" hreflang="fr" rel="alternate"/>
<link href="https://companiesmarketcap.com/" hreflang="en-US" rel="alternate"/>
<link href="https://companiesmarketcap.com/eur/" hreflang="en-IE" rel="alternate"/>
<link href="https://companiesmarketcap.com/inr/" hreflang="en-IN" rel="alternate"/>
<link href="https://companiesmarketcap.com/gbp/" hreflang="en-GB" rel="alternate"/>
<link href="https://companiesmarketcap.com/cad/" hreflang="en-CA" rel="alternate"/>
<link href="https://companiesmarketcap.com/aud/" hreflang="en-AU" rel="alternate"/>
<link href="https://companiesmarketcap.com/nzd/" hreflang="en-NZ" rel="alternate"/>
<link href="https://companiesmarketcap.com/hkd/" hreflang="en-HK" rel="alternate"/>
<link href="https://companiesmarketcap.com/sgd/" hreflang="en-SG" rel="alternate"/>
<link href="https://companiesmarketcap.com/inr/" rel="canonical"/>
<meta content="https://companiesmarketcap.com/inr/" property="og:url"/>
<meta content="INDEX,FOLLOW" name="robots"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/img/icons/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="en-IN" http-equiv="content-language"/>
<meta content="Companies ranked by Market Cap - CompaniesMarketCap.com" property="og:title"/><meta content="website" property="og:type"/>
<meta content="Ranking the world's top companies by market cap, market value, revenue and many more metrics" property="og:description"/>
<meta content="https://companiesmarketcap.com/logo.png" property="og:image"/>
<meta content="Ranking the world's top companies by market cap, market value, revenue and many more metrics" name="description"/>
<link href="/bt-replacement.css?v=9" rel="stylesheet" type="text/css"/>
<link href="/css/style.css?v=348" rel="stylesheet" type="text/css"/>
<script>
current_locale = "inr";
current_locale_path = "/inr";

current_marketcap_path = "marketcap";
</script>
<script async="" src="https://cdn.fuseplatform.net/publift/tags/2/3432/fuse.js"></script></head>
<body class="cmkt" id="cmkt">
<div class="row site-header-row">
<div class="site-header">
<span style="display: inline-flex; margin-top: 2px;">
<span class="max-width-720px-hidden">
                        Companies: <span class="font-weight-bold">11,075</span>
                        total market cap: <span class="font-weight-bold"><a class="total-mcap-link" href="/total-marketcap/">₹14374.448 T</a></span>
</span>
</span>
<div class="header-actions">
<a class="header-button sign-in-button sign-in" href="#">Sign In</a>
<div class="dropdown currency-dropdown">
<a aria-expanded="false" aria-haspopup="true" class="header-button dropdown-toggle" data-toggle="dropdown" href="#" id="languageDropdown">
                        🇺🇸 <span class="responsive-shown-inline">EN</span><span class="responsive-hidden">English</span> </a>
<div aria-labelledby="languageDropdown" class="dropdown-menu currency-menu">
<a class="dropdown-item" href="/de/" onclick="document.cookie = 'pref_language=DE;  max-age=91536000000; path=/;';">🇩🇪 Deutsch</a><a class="dropdown-item" href="/fr/" onclick="document.cookie = 'pref_language=FR;  max-age=91536000000; path=/;';">🇫🇷 Français</a> </div>
</div>
<div class="dropdown currency-dropdown">
<a aria-expanded="false" aria-haspopup="true" class="header-button dropdown-toggle" data-toggle="dropdown" href="#" id="currencyDropdown">
                        ₹ INR                        </a>
<div aria-labelledby="currencyDropdown" class="dropdown-menu currency-menu">
<a class="dropdown-item" href="/" onclick="document.cookie = 'pref_currency=USD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">USD</span><span class="currency-flag">🇺🇸</span></a><a class="dropdown-item" href="/eur/" onclick="document.cookie = 'pref_currency=EUR;  max-age=91536000000; path=/;';"><span class="symbol">€</span><span class="currency-code">EUR</span><span class="currency-flag">🇪🇺</span></a><a class="dropdown-item" href="/gbp/" onclick="document.cookie = 'pref_currency=GBP;  max-age=91536000000; path=/;';"><span class="symbol">£</span><span class="currency-code">GBP</span><span class="currency-flag">🇬🇧</span></a><a class="dropdown-item" href="/cad/" onclick="document.cookie = 'pref_currency=CAD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">CAD</span><span class="currency-flag">🇨🇦</span></a><a class="dropdown-item" href="/aud/" onclick="document.cookie = 'pref_currency=AUD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">AUD</span><span class="currency-flag">🇦🇺</span></a><a class="dropdown-item" href="/nzd/" onclick="document.cookie = 'pref_currency=NZD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">NZD</span><span class="currency-flag">🇳🇿</span></a><a class="dropdown-item" href="/hkd/" onclick="document.cookie = 'pref_currency=HKD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">HKD</span><span class="currency-flag">🇭🇰</span></a><a class="dropdown-item" href="/sgd/" onclick="document.cookie = 'pref_currency=SGD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">SGD</span><span class="currency-flag">🇸🇬</span></a> </div>
</div>
<a class="dark-hidden" href="#" id="light-off-btn" title="change to dark mode">
<svg height="16" viewbox="0 70 1000 1000" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M525.3,989.5C241.2,989.5,10,758.3,10,474.1c0-196.8,109.6-373.6,285.9-461.4c7.9-3.9,17.5-2.4,23.7,3.8c6.2,6.2,7.9,15.8,4,23.7c-32.2,65.4-48.5,135.7-48.5,208.9c0,261.4,212.7,474.1,474.1,474.1c74,0,145-16.7,211-49.5c7.9-3.9,17.5-2.4,23.7,3.8c6.3,6.3,7.9,15.8,3.9,23.7C900.5,879,723.3,989.5,525.3,989.5z"></path>
</svg>
</a>
<a class="dark-shown" href="#" id="light-on-btn" title="change to light mode">
<svg height="16" viewbox="10 10 220 220" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M120,189.697c-38.492,0-69.696-31.205-69.696-69.697S81.508,50.303,120,50.303c38.494,0,69.699,31.205,69.699,69.697 S158.494,189.697,120,189.697z M203.975,140L240,120l-36.025-20V140z M36.025,100L0,120l36.025,20V100z M120,240l20-36.025h-40 L120,240z M120,0l-20,36.025h40L120,0z M46.481,165.238l-11.333,39.615l39.616-11.33L46.481,165.238z M165.238,46.477l28.283,28.285 l11.332-39.613L165.238,46.477z M35.148,35.148L46.48,74.762l28.283-28.285L35.148,35.148z M165.238,193.523l39.615,11.33 l-11.332-39.615L165.238,193.523z"></path>
</svg>
</a>
</div>
</div>
</div>
<nav class="navbar nav-bar-companiesmarketcap navbar-expand-lg navbar-light">
<div class="navbar-collapse-container">
<button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
<span class="navbar-toggler-icon"></span>
</button>
<form class="search-form form-inline">
<input aria-label="Company name, ticker..." autocomplete="off" class="form-control search-input" id="search-input" placeholder="Company name, ticker..." type="search"/>
<button class="btn-search" disabled="" onclick="return false;" type="submit"><svg height="18" viewbox="0 0 14 14" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" stroke="#6c6c6c" stroke-width="2"><path d="M11.29 11.71l-4-4"></path><circle cx="5" cy="5" r="4"></circle></g></svg></button>
<div class="typeahead-search-results" id="typeahead-search-results"></div>
</form>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<a class="responsive-hidden" href="/" title="CompaniesMarketCap.com - companies ranked by market capitalization">
<div class="companiesmarketcap-logo"></div>
</a>
<ul class="navbar-nav">
<li class="nav-item">
<a class="nav-link nav-link-companiesmarketcap" href="/inr/">Global ranking</a>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-countries">Ranking by countries</a>
<div aria-labelledby="dropdown-countries" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<h5>America</h5>
<a class="dropdown-item" href="/inr/usa/largest-companies-in-the-usa-by-market-cap/">🇺🇸 United States</a>
<a class="dropdown-item" href="/inr/canada/largest-companies-in-canada-by-market-cap/">🇨🇦 Canada</a>
<a class="dropdown-item" href="/inr/mexico/largest-companies-in-mexico-by-market-cap/">🇲🇽 Mexico</a>
<a class="dropdown-item" href="/inr/brazil/largest-companies-in-brazil-by-market-cap/">🇧🇷 Brazil</a>
<a class="dropdown-item" href="/inr/chile/largest-companies-in-chile-by-market-cap/">🇨🇱 Chile</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Europe</h5>
<a class="dropdown-item" href="/inr/european-union/largest-companies-in-the-eu-by-market-cap/">🇪🇺 European Union</a>
<a class="dropdown-item" href="/inr/germany/largest-companies-in-germany-by-market-cap/">🇩🇪 Germany</a>
<a class="dropdown-item" href="/inr/united-kingdom/largest-companies-in-the-uk-by-market-cap/">🇬🇧 United Kingdom</a>
<a class="dropdown-item" href="/inr/france/largest-companies-in-france-by-market-cap/">🇫🇷 France</a>
<a class="dropdown-item" href="/inr/spain/largest-companies-in-spain-by-market-cap/">🇪🇸 Spain</a>
<a class="dropdown-item" href="/inr/netherlands/largest-companies-in-the-netherlands-by-market-cap/">🇳🇱 Netherlands</a>
<a class="dropdown-item" href="/inr/sweden/largest-companies-in-sweden-by-market-cap/">🇸🇪 Sweden</a>
<a class="dropdown-item" href="/inr/italy/largest-companies-in-italy-by-market-cap/">🇮🇹 Italy</a>
<a class="dropdown-item" href="/inr/switzerland/largest-companies-in-switzerland-by-market-cap/">🇨🇭 Switzerland</a>
<a class="dropdown-item" href="/inr/poland/largest-companies-in-poland-by-market-cap/">🇵🇱 Poland</a>
<a class="dropdown-item" href="/inr/finland/largest-companies-in-finland-by-market-cap/">🇫🇮 Finland</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Asia</h5>
<a class="dropdown-item" href="/inr/china/largest-companies-in-china-by-market-cap/">🇨🇳 China</a>
<a class="dropdown-item" href="/inr/japan/largest-companies-in-japan-by-market-cap/">🇯🇵 Japan</a>
<a class="dropdown-item" href="/inr/south-korea/largest-companies-in-south-korea-by-market-cap/">🇰🇷 South Korea</a>
<a class="dropdown-item" href="/inr/hong-kong/largest-companies-in-hong-kong-by-market-cap/">🇭🇰 Hong Kong</a>
<a class="dropdown-item" href="/inr/singapore/largest-companies-in-singapore-by-market-cap/">🇸🇬 Singapore</a>
<a class="dropdown-item" href="/inr/indonesia/largest-companies-in-indonesia-by-market-cap/">🇮🇩 Indonesia</a>
<a class="dropdown-item" href="/inr/india/largest-companies-in-india-by-market-cap/">🇮🇳 India</a>
<a class="dropdown-item" href="/inr/malaysia/largest-companies-in-malaysia-by-market-cap/">🇲🇾 Malaysia</a>
<a class="dropdown-item" href="/inr/taiwan/largest-companies-in-taiwan-by-market-cap/">🇹🇼 Taiwan</a>
<a class="dropdown-item" href="/inr/thailand/largest-companies-in-thailand-by-market-cap/">🇹🇭 Thailand</a>
<a class="dropdown-item" href="/inr/vietnam/largest-companies-in-vietnam-by-market-cap/">🇻🇳 Vietnam</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Others</h5>
<a class="dropdown-item" href="/inr/australia/largest-companies-in-australia-by-market-cap/">🇦🇺 Australia</a>
<a class="dropdown-item" href="/inr/new-zealand/largest-companies-in-new-zealand-by-market-cap/">🇳🇿 New Zealand</a>
<a class="dropdown-item" href="/inr/israel/largest-companies-in-israel-by-market-cap/">🇮🇱 Israel</a>
<a class="dropdown-item" href="/inr/saudi-arabia/largest-companies-in-saudi-arabia-by-market-cap/">🇸🇦 Saudi Arabia</a>
<a class="dropdown-item" href="/inr/turkey/largest-companies-in-turkey-by-market-cap/">🇹🇷 Turkey</a>
<a class="dropdown-item" href="/inr/russia/largest-companies-in-russia-by-market-cap/">🇷🇺 Russia</a>
<a class="dropdown-item" href="/inr/south-africa/largest-companies-in-south-africa-by-market-cap/">🇿🇦 South Africa</a>
<a class="dropdown-item" href="/inr/all-countries/"><strong>&gt;&gt; All Countries</strong></a>
</div>
</div>
</div>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-categories">Ranking by categories</a>
<div aria-labelledby="dropdown-categories" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<a class="dropdown-item" href="/inr/assets-by-market-cap/">🏆 All assets by Market Cap</a>
<a class="dropdown-item" href="/inr/automakers/largest-automakers-by-market-cap/">🚗 Automakers</a>
<a class="dropdown-item" href="/inr/airlines/largest-airlines-by-market-cap/">✈️  Airlines</a>
<a class="dropdown-item" href="/inr/airports/largest-airport-operating-companies-by-market-cap/">🛫 Airports</a>
<a class="dropdown-item" href="/inr/aircraft-manufacturers/largest-aircraft-manufacturers-by-market-cap/">✈️  Aircraft manufacturers</a>
<a class="dropdown-item" href="/inr/banks/largest-banks-by-market-cap/">🏦 Banks</a>
<a class="dropdown-item" href="/inr/hotels/largest-hotel-companies-by-market-cap/">🏨 Hotels</a>
<a class="dropdown-item" href="/inr/pharmaceuticals/largest-pharmaceutical-companies-by-market-cap/">💊 Pharmaceuticals</a>
<a class="dropdown-item" href="/inr/e-commerce/largest-e-commerce-companies-by-market-cap/">🛒 E-Commerce</a>
<a class="dropdown-item" href="/inr/healthcare/largest-healthcare-companies-by-market-cap/">⚕️ Healthcare</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/inr/delivery-services/largest-delivery-companies-by-market-cap/">📦 Courier services</a>
<a class="dropdown-item" href="/inr/media-press/largest-media-and-press-companies-by-market-cap/">📰 Media/Press</a>
<a class="dropdown-item" href="/inr/alcoholic-beverages/largest-alcoholic-beverage-companies-by-market-cap/">🍷 Alcoholic beverages</a>
<a class="dropdown-item" href="/inr/beverages/largest-beverage-companies-by-market-cap/">🥤 Beverages</a>
<a class="dropdown-item" href="/inr/clothing/largest-clothing-companies-by-market-cap/">👚 Clothing</a>
<a class="dropdown-item" href="/inr/mining/largest-mining-companies-by-market-cap/">⛏️ Mining</a>
<a class="dropdown-item" href="/inr/railways/largest-railways-companies-by-market-cap/">🚂 Railways</a>
<a class="dropdown-item" href="/inr/insurance/largest-insurance-companies-by-market-cap/">🏦 Insurance</a>
<a class="dropdown-item" href="/inr/real-estate/largest-real-estate-companies-by-market-cap/">🏠 Real estate</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/inr/ports/largest-port-operating-companies-by-market-cap/">⚓ Ports</a>
<a class="dropdown-item" href="/inr/professional-services/largest-professional-service-companies-by-market-cap/">💼 Professional services</a>
<a class="dropdown-item" href="/inr/food/largest-food-companies-by-market-cap/">🍴 Food</a>
<a class="dropdown-item" href="/inr/restaurant-chains/largest-restaurant-chain-companies-by-market-cap/">🍔 Restaurant chains</a>
<a class="dropdown-item" href="/inr/software/largest-software-companies-by-market-cap/">‍💻 Software</a>
<a class="dropdown-item" href="/inr/semiconductors/largest-semiconductor-companies-by-market-cap/">📟 Semiconductors</a>
<a class="dropdown-item" href="/inr/tobacco/largest-tobacco-companies-by-market-cap/"> 🚬 Tobacco</a>
<a class="dropdown-item" href="/inr/financial-services/largest-financial-service-companies-by-market-cap/">💳 Financial services</a>
<a class="dropdown-item" href="/inr/oil-gas/largest-oil-and-gas-companies-by-market-cap/">🛢 Oil&amp;Gas</a>
<a class="dropdown-item" href="/inr/electricity/largest-electricity-companies-by-market-cap/">🔋 Electricity</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/inr/chemicals/largest-chemical-companies-by-market-cap/">🧪 Chemicals</a>
<a class="dropdown-item" href="/inr/investment/largest-investment-companies-by-market-cap/">💰 Investment</a>
<a class="dropdown-item" href="/inr/telecommunication/largest-telecommunication-companies-by-market-cap/">📡 Telecommunication</a>
<a class="dropdown-item" href="/inr/retail/largest-retail-companies-by-market-cap/">🛍️ Retail</a>
<a class="dropdown-item" href="/inr/internet/largest-internet-companies-by-market-cap/">🖥️ Internet</a>
<a class="dropdown-item" href="/inr/construction/largest-construction-companies-by-market-cap/">🏗 Construction</a>
<a class="dropdown-item" href="/inr/video-games/largest-video-game-companies-by-market-cap/">🎮 Video Game</a>
<a class="dropdown-item" href="/inr/tech/largest-tech-companies-by-market-cap/">💻 Tech</a>
<a class="dropdown-item" href="/inr/artificial-intelligence/largest-ai-companies-by-marketcap/">🦾 AI</a>
<a class="dropdown-item" href="/inr/all-categories/"><strong>&gt;&gt; All Categories</strong></a>
</div>
</div>
</div>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-categories">ETFs</a>
<div aria-labelledby="dropdown-categories" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<a class="dropdown-item" href="/inr/etfs/largest-etfs-by-marketcap/">🏆 All ETFs</a>
<a class="dropdown-item" href="/inr/bond-etfs/largest-bond-etfs-by-marketcap/">🏛️ Bond ETFs</a>
<a class="dropdown-item" href="/inr/dividend-and-income-etfs/largest-dividend-etfs-by-marketcap/">％ Dividend ETFs</a>
<a class="dropdown-item" href="/inr/bitcoin-etfs/largest-bitcoin-etfs-by-marketcap/">₿ Bitcoin ETFs</a>
<a class="dropdown-item" href="/inr/ethereum-etfs/largest-ethereum-etfs-by-marketcap/">♢ Ethereum ETFs</a>
<a class="dropdown-item" href="/inr/cryptocurrency-etfs/largest-crypto-etfs-by-marketcap/">🪙 Crypto Currency ETFs</a>
<a class="dropdown-item" href="/inr/gold-etfs/largest-gold-etfs-by-marketcap/">🥇 Gold ETFs &amp; ETCs</a>
<a class="dropdown-item" href="/inr/silver-etfs/largest-silver-etfs-by-marketcap/">🥈 Silver ETFs &amp; ETCs</a>
<a class="dropdown-item" href="/inr/oil-etfs/largest-oil-etfs-by-marketcap/">🛢️ Oil ETFs &amp; ETCs</a>

In [7]:
soup.find_all('table')

[<table class="default-table table marketcap-table dataTable" style="width:100%">
 <thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [8]:
soup.find('table', class_ ='default-table table marketcap-table dataTable' )

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [9]:
table = soup.find('table', class_ ='default-table table marketcap-table dataTable' )

In [10]:
table

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [11]:
titles = table.find_all('th')

In [12]:
titles

[<th class="th-id-1" tid="1"></th>,
 <th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th>,
 <th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th>,
 <th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th>,
 <th class="th-id-5 th-price sorting text-right" tid="5">Price</th>,
 <th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th>,
 <th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th>,
 <th class="th-id-8 th-country sorting" tid="8">Country</th>]

In [13]:
table_titles = [title.text.strip() for title in titles[1:]]

print(table_titles)

['Rank', 'Name', 'Market Cap', 'Price', 'Today', 'Price (30 days)', 'Country']

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame(columns = table_titles)

In [16]:
df

Empty DataFrame
Columns: [Rank, Name, Market Cap, Price, Today, Price (30 days), Country]
Index: []

In [17]:
column_data = table.find_all('tr')

for row in column_data:
    row_data = row.find_all('td')
    
    # [1:] skips the first 'td' (the favorite column)
    individual_row_data = [data.text.strip() for data in row_data[1:]] 
    
    if len(individual_row_data) == len(df.columns):
        length = len(df)
        df.loc[length] = individual_row_data

In [18]:
df

,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,1,NVIDIANVDA,₹477.106 T,"₹19,698",2.34%,,🇺🇸 USA
1,2,AppleAAPL,₹445.823 T,"₹30,354",0.69%,,🇺🇸 USA
2,3,Alphabet (Google)GOOG,₹411.677 T,"₹33,737",0.61%,,🇺🇸 USA
3,4,MicrosoftMSFT,₹277.360 T,"₹37,338",1.41%,,🇺🇸 USA
4,5,AmazonAMZN,₹254.828 T,"₹23,689",0.99%,,🇺🇸 USA
...,...,...,...,...,...,...,...
95,96,SantanderSAN,₹18.692 T,"₹1,306",1.55%,,🇪🇸 Spain
96,97,InditexITX.MC,₹18.619 T,"₹5,980",0.29%,,🇪🇸 Spain
97,98,AmphenolAPH,₹18.522 T,"₹15,056",1.00%,,🇺🇸 USA
98,99,McDonaldMCD,₹18.460 T,"₹25,982",1.04%,,🇺🇸 USA
99,100,AmgenAMGN,₹18.411 T,"₹34,115",1.81%,,🇺🇸 USA

In [25]:
df.to_csv(r'C:\Users\omkar\OneDrive\Desktop\Data Analyst\Python\Demo\csv files\topcomp.csv', index = False)