# Scraping Data From a Real Website + Pandas 2

In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = 'https://companiesmarketcap.com/inr/'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [4]:
soup

In [10]:
soup.find_all('table')

[<table class="default-table table marketcap-table dataTable" style="width:100%">
 <thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [13]:
soup.find('table', class_ ='default-table table marketcap-table dataTable' )

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [20]:
table = soup.find('table', class_ ='default-table table marketcap-table dataTable' )

In [21]:
table

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [22]:
titles = table.find_all('th')

In [23]:
titles

[<th class="th-id-1" tid="1"></th>,
 <th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th>,
 <th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th>,
 <th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th>,
 <th class="th-id-5 th-price sorting text-right" tid="5">Price</th>,
 <th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th>,
 <th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th>,
 <th class="th-id-8 th-country sorting" tid="8">Country</th>]

In [25]:
table_titles = [title.text.strip() for title in titles[1:]]

print(table_titles)

['Rank', 'Name', 'Market Cap', 'Price', 'Today', 'Price (30 days)', 'Country']

In [30]:
import pandas as pd

In [37]:
df = pd.DataFrame(columns = table_titles)

In [38]:
df

Empty DataFrame
Columns: [Rank, Name, Market Cap, Price, Today, Price (30 days), Country]
Index: []

In [55]:
column_data = table.find_all('tr')

for row in column_data:
    row_data = row.find_all('td')
    
    # [1:] skips the first 'td' (the favorite column)
    individual_row_data = [data.text.strip() for data in row_data[1:]] 
    
    if len(individual_row_data) == len(df.columns):
        length = len(df)
        df.loc[length] = individual_row_data

In [56]:
df

,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,1,NVIDIANVDA,₹480.973 T,"₹19,858",1.55%,,🇺🇸 USA
1,2,AppleAAPL,₹444.856 T,"₹30,288",0.47%,,🇺🇸 USA
2,3,Alphabet (Google)GOOG,₹410.965 T,"₹33,679",0.78%,,🇺🇸 USA
3,4,MicrosoftMSFT,₹277.651 T,"₹37,377",1.51%,,🇺🇸 USA
4,5,AmazonAMZN,₹255.836 T,"₹23,783",1.39%,,🇺🇸 USA
...,...,...,...,...,...,...,...
95,96,Seagate TechnologySTX,₹18.746 T,"₹83,605",3.94%,,🇮🇪 Ireland
96,97,SantanderSAN,₹18.727 T,"₹1,308",1.37%,,🇪🇸 Spain
97,98,InditexITX.MC,₹18.639 T,"₹5,987",0.18%,,🇪🇸 Spain
98,99,AmphenolAPH,₹18.606 T,"₹15,125",0.55%,,🇺🇸 USA
99,100,McDonaldMCD,₹18.471 T,"₹25,997",0.98%,,🇺🇸 USA